### PR TITLE
Various improvements + Benchmarks

### LINKED ISSUE #1: Benchmarking against fillRect
Hi! Coming from the YouTube video. I am opening this issue as a reminder for setting up a benchmark.

### PR DESCRIPTION
**Pull request by aminya**
- Separated HTML from JS
- Using `npm` as a script runner
- Added build scripts using clang, emsdk, wasm2wat, asmjs
- Added serve script
- Added clean script
- Added readme
- Added benchmarks against fillRect. Fixes #1 

The Tweet about the benchmark:
https://twitter.com/AminYa74/status/1349226315589758982

### CODE REVIEW

**Comment by aminya** [comment]
@maniyar1 Could you check this out?

**Comment by maniyar1** [comment]
Sorry for the late response, but these look awesome! I'll take a look further tomorrow and if it all looks good I'll PR it in. Thanks for doing this.

**Comment by maniyar1** [comment]
Alright, after taking an extensive look I think I'm going to put what you're using npm for in a shell script, is there a particular reason you used npm? I'm personally not a fan of the dependency. I think a simple standards-compliant sh script will be portable enough for most platforms. The rest seems intuitive and good to me. If you don't have any objections to the shell script I'll put that together and push that.

**Comment by aminya** [comment]
Npm is "the web package manager", and it is more portable than Bash. For example, Windows which has more than 80% of the market share does not support bash.

**Comment by maniyar1** [comment]
Alright, sorry for dropping off for a bit.

> Npm is "the web package manager"

This is true, and I appreciate that npm is the standard for managing packages, but there are no packages to manage here.

> For example, Windows which has more than 80% of the market share does not support bash.

This is only true in part, git on windows comes with git bash, which will be more than enough to run the simple shell script this requires. Anyone cloning this repo will probably have it handy, or could use WSL. I could write a python/bat/lua script or something, but I really think since it's a one-liner it'll be fine. I'll make sure to add a note to the README for Windows users.

**Comment by aminya** [comment]
No problem. I made this PR as a courtesy.

**Pull request closed without merging**
